# Makefile
 
CC=gcc -fsanitize=address
CPPFLAGs=
CFLAGS= -Wall -Wextra -std=c99 -O2 -g -pthread
LDFLAGS=
LDLIBS=
 
SRC1 = server_v_1.0.c
OBJ1 = ${SRC1:.c=.o}

all: server_v_1.0
 
clean:
	rm -f *.o
 
# END
