# Makefile
 
CC=gcc -fsanitize=address
CPPFLAGs=
CFLAGS= -Wall -Wextra -std=c99 -O2 -g
LDFLAGS=
LDLIBS=
 
SRC1 = Client_Retarded_IRC.c
OBJ1 = ${SRC1:.c=.o}

all: Client_Retarded_IRC
 
clean:
	rm -f *.o
 
# END
